### ISSUE TITLE
Questions: Process Function Matching

### ISSUE THREAD

**Issue by pwhittin** [suprematic/otplike#25]
Consider a process function like:

```clojure
(op/proc-defn
  event-loop
  [server event-name to-go]
  (op/receive!
    [server ref :cancel] (op/! server [ref :ok])
    (after to-go (op/! server [:done event-name])))) 
```

A couple of questions:
1. Will the match `[server ref :cancel]` only match messages from the specific value of `server` passed to event-loop, any value of ref and `:cancel`?
1. What happens to non-matching messages that might be sent to event-loop?
1. Should one do something to handle non-matching messages?

**Comment by sskorokhodov** [comment]
>1. Will the match `[server ref :cancel]` only match messages from the specific value of `server` passed to event-loop, any value of ref and `:cancel`?

Yes. It works exactly like [clojure/core.match](https://github.com/clojure/core.match/wiki/Basic-usage) does.

>2. What happens to non-matching messages that might be sent to event-loop?

If message doesn't match, `receive!` will throw `IllegalArgumentException`. Once again as `clojure/core.match` does.

>3. Should one do something to handle non-matching messages? 

It depends on what desired behavior is:

1. The default way is to simply skip handling of unexpected messages and crash. Unexpected messages are usually sing of bugs. This way works if everything is linked properly.
2. Sometimes one expects arbitrary messages and want to tolerate them. In such cases "catch all" clause is the way to go.

It's not a final decision, but I really want to _add_ "selective receive" working the same way as erlang's `receive` does. Using selective receive instead of `receive!` one can wait for specific message leaving other messages untouched.
