### ISSUE TITLE
circuit-breaker-like supervision?

### ISSUE THREAD

**Issue by xificurC** [suprematic/otplike#44]
I'm thinking of porting some code to otplike but need to keep its behavior as much as possible. Right now I have 3 threads that communicate through 2 buffered streams. Each thread is started by a function called `supervise` that runs a given thunk in a try-catch and restarts the thunk in case of failure. The restart strategy can be e.g. to wait `(min (long (* last-sleep 1.5)) 5-minutes)` with a start of 5 seconds, giving an increasing waiting time (5, 7, 10, 15, ... , 300, 300, 300 ...).

I might not want to keep the separation of supervising (i.e. each thread can restart by itself) because supervising the whole with `:one-for-all` might yield simpler and more robust code. But I need to be able to start the whole thing and keep restarting it in case of failures with similar behavior as described above to ease the load on the system.

I see some knobs on the supervisor, namely `:intensity` and `:period`, to control when should the supervisor fail, but this doesn't address my questions.

Is this an uncommon request? Or is this usually handled somehow differently? Maybe I'm expecting the supervisor to do something that it's not supposed to. For the simplest example - if N supervised trees are streaming data from a database and the connection dies (e.g. the database is restarting) and it's down for 2 minutes I don't want all of them to keep restarting in a busy loop, nor do I want the supervisors to fail, just to keep trying until they succeed.

**Comment by sskorokhodov** [comment]
Unfortunately, neither otplike nor Erlang gives you a circuit-breaker behavior out of the box. There are libraries implementing different circuit-breakers in Erlang.

As for otplike, you can use an intermediate gen-server.

The gen-server:

- is started by a supervisor instead of the worker
- traps exits
- starts the worker with linking

When it receives an exit signal as a message (through the `handle-info` callback) like `[:EXIT worker-pid reason]`, it returns `[:noreply state timeout-ms]`. If nothing else happens, after `timeout-ms` it receives another message `:timeout`. At this moment it should try to start the worker again.

You can implement any strategy you want keeping the required information in the gen-server's state. Don't forget to handle the errors when starting the worker.

**Comment by xificurC** [comment]
My thinking was that if there's already a restart logic written (based on supplied `:intensity` and `:period`) it might be easy to swap that out for something custom. Looking at the source code I see this logic implemented in [`add-restart`](https://github.com/suprematic/otplike/blob/bc9d4e82c14053fac8a0ec141eaca897dd2cfe9b/src/otplike/supervisor.clj#L491), which is called exactly once later. It seems it needs to return its new state and either `:shutdown` or `:continue`. I could easily swap that logic out with another function that would wait some time before returning `:continue` without disrupting the rest of the code around it.

Does this sound reasonable? This would allow reusing all of the supervisor's logic as opposed to writing a supervisor-like-think via a genserver. From my (inexperienced) perspective this also sounds like the right place to put the logic. In theory a `:restart-fn` argument next to `:intensity` and `:period` and an if-check for it before calling the built-in one would be enough to extend the supervisor to allow any kind of restarting logic while keeping backwards compatibility.

**Comment by sskorokhodov** [comment]
First of all - I really appreciate the intention.

But I have several things to consider before doing something:

- "supervisor" is a thought off and well known Erlang behavior. Otplike provides an almost exact copy of the Erlang's version. You can open any Erlang book describing how supervisor works and be sure that that knowledge is applicable to otplike. It also is quite well tested in its current implementation.
- Adding a time aspect into the restart policy rises a lot of questions to be answered before changing anything. It also needs to be documented and tested.
- Adding a simple "circuit-breaker" which is to be parameterized by the target gen-server start-fn and is launched by a supervisor instead of the target, is quite simple, can be tested separately and doesn't break the expectations of how supervisor works. That also allows having much more sophisticated restart strategies than "swapping out" a function would possibly allow.
- "supervisor" tries to keep everything up and running. It supposes that it's children either run or need to be (re)started. There is no concept of "delay" here because it's just not a supervisor's responsibility.

A default "circuit-breaker" can be even included in otplike because it is a very useful concept. But unlike such a core behavior as supervisor it doesn't have to be fully tested and documented at first.

Although if you still think that it's worth doing, I'm open to a discussion.

**Comment by xificurC** [comment]
Thank you for these thorough explanations and taking time to consider my requests even though I'm uneducated in the field of Erlang/OTP (I'm reading a book!).

If you're saying you nor the Erlang board think this belongs in the supervisor then I will accept that as an answer. Surely you and they thought enough about the options before making a decision.

The only reason I felt like it should belong there because I'd only need to change one function call whereas I didn't yet fully grok your explanation, where it seemed I need to do much more work like handle starting errors and such. If you're saying it's pretty simple I hope I'll be able to whip it up myself :)

Thank you for your time, I consider this "issue" closed
